// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VSLab.Data;

#nullable disable

namespace VSLab.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    [Migration("20230522143345_TestMigrations")]
    partial class TestMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VSLab.Data.Security.tblUserProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("tblUserProfiles");
                });

            modelBuilder.Entity("VSLab.Data.tblChatMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("tblChatMessages");
                });

            modelBuilder.Entity("VSLab.Data.tblChessChampion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ChessPlayerID")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveYears")
                        .HasColumnType("integer");

                    b.Property<int>("Current")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastTrophy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxRating")
                        .HasColumnType("integer");

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ChessPlayerID");

                    b.ToTable("tblChessChampions");
                });

            modelBuilder.Entity("VSLab.Data.tblChessParticipation", b =>
                {
                    b.Property<int>("ChessTournamentID")
                        .HasColumnType("integer");

                    b.Property<int>("ChessPlayerID")
                        .HasColumnType("integer");

                    b.Property<string>("DateSigned")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DurationPlayed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChessTournamentID", "ChessPlayerID");

                    b.HasIndex("ChessPlayerID");

                    b.ToTable("tblChessParticipations");
                });

            modelBuilder.Entity("VSLab.Data.tblChessPlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsMaster")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("tblChessPlayers");
                });

            modelBuilder.Entity("VSLab.Data.tblChessTournament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("PrizeMoney")
                        .HasColumnType("integer");

                    b.Property<string>("Trophy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("tblChessTournaments");
                });

            modelBuilder.Entity("VSLab.Data.tblChessChampion", b =>
                {
                    b.HasOne("VSLab.Data.tblChessPlayer", "ChessPlayer")
                        .WithMany("ChessChampions")
                        .HasForeignKey("ChessPlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChessPlayer");
                });

            modelBuilder.Entity("VSLab.Data.tblChessParticipation", b =>
                {
                    b.HasOne("VSLab.Data.tblChessPlayer", "ChessPlayer")
                        .WithMany("PlayerParticipations")
                        .HasForeignKey("ChessPlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSLab.Data.tblChessTournament", "ChessTournament")
                        .WithMany("TournamentParticipations")
                        .HasForeignKey("ChessTournamentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChessPlayer");

                    b.Navigation("ChessTournament");
                });

            modelBuilder.Entity("VSLab.Data.tblChessPlayer", b =>
                {
                    b.HasOne("VSLab.Data.Security.tblUserProfile", "TblUser")
                        .WithMany("ChessPlayers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblUser");
                });

            modelBuilder.Entity("VSLab.Data.tblChessTournament", b =>
                {
                    b.HasOne("VSLab.Data.Security.tblUserProfile", "TblUser")
                        .WithMany("ChessTournaments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblUser");
                });

            modelBuilder.Entity("VSLab.Data.Security.tblUserProfile", b =>
                {
                    b.Navigation("ChessPlayers");

                    b.Navigation("ChessTournaments");
                });

            modelBuilder.Entity("VSLab.Data.tblChessPlayer", b =>
                {
                    b.Navigation("ChessChampions");

                    b.Navigation("PlayerParticipations");
                });

            modelBuilder.Entity("VSLab.Data.tblChessTournament", b =>
                {
                    b.Navigation("TournamentParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
