﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace VSLab
{
    public partial class MLModel
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"id", @"id"),new InputOutputColumnPair(@"rating", @"rating"),new InputOutputColumnPair(@"tournaments", @"tournaments"),new InputOutputColumnPair(@"champions", @"champions")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"id",@"rating",@"tournaments",@"champions"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=9,NumberOfIterations=6,MinimumExampleCountPerLeaf=20,LearningRate=0.917261246399143,LabelColumnName=@"championNext",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.122950039657781,FeatureFraction=0.965231819608788,L1Regularization=5.61177311667497E-10,L2Regularization=0.999999776672986},MaximumBinCountPerFeature=279}));

            return pipeline;
        }
    }
}
